#!/bin/bash

# json -> bin
# https://config.qmk.fm/#/cantor/LAYOUT_split_3x6_3


if [[ -z "$1" ]] ; then
	echo "Missing firmware bin file parameter"
	exit
fi

echo "Press UpperLeft key and plug the keyboard!"
read

dfu-util -l

read

dfu-util --device 0483:df11 --alt 0 --dfuse-address 0x08000000 --download "$1"
